-- modules/globals.lua
local G = {}
G.MAP_WIDTH = 1000; G.MAP_HEIGHT = 1000; G.CHUNK_SIZE = 16; G.TILE_SIZE = 32
G.HEX_RADIUS = 24; G.HEX_WIDTH = math.sqrt(3)*G.HEX_RADIUS; G.HEX_HEIGHT = 2*G.HEX_RADIUS; G.HEX_HORZ_SPACING = G.HEX_WIDTH; G.HEX_VERT_SPACING = G.HEX_HEIGHT*3/4
G.WORLD_PIXEL_WIDTH = G.MAP_WIDTH*G.HEX_HORZ_SPACING; G.WORLD_PIXEL_HEIGHT = G.MAP_HEIGHT*G.HEX_VERT_SPACING
G.PLAYER_COLLISION_W = 20; G.PLAYER_COLLISION_H = 24; G.PLAYER_COLLISION_OX = 10; G.PLAYER_COLLISION_OY = 32
return G