-- modules/data.lua
local Data = {}

Data.Items = {wood={name="Wood"},stone={name="Stone"},flint={name="Flint"},fiber={name="Fiber"},herb={name="Herb"},coal={name="Coal"},copper_ore={name="Copper Ore"},tin_ore={name="Tin Ore"},iron_ore={name="Iron Ore"},tree={name="Tree",yield={wood=3}},rock={name="Rock",yield={stone=2,flint=1}},fiber_plant={name="Fiber Plant",yield={fiber=3}},herb_plant={name="Herb Plant",yield={herb=2}},coal_vein={name="Coal Vein",yield={coal=3},requires="pickaxe"},copper_vein={name="Copper Vein",yield={copper_ore=2},requires="pickaxe"},tin_vein={name="Tin Vein",yield={tin_ore=2},requires="pickaxe"},iron_vein={name="Iron Vein",yield={iron_ore=2},requires="pickaxe"},stone_axe={name="Stone Axe",recipe={flint=2,wood=2,fiber=2}},pickaxe={name="Pickaxe",recipe={wood=2,stone=3}},stone_wall={name="Stone Wall",recipe={stone=2},buildable=true},campfire={name="Campfire",recipe={wood=5},buildable=true}}
Data.baseInventory = {}; for k,d in pairs(Data.Items) do Data.baseInventory[k] = 0 end

Data.Biomes = {deep_water={name="Deep Water",color={0.1,0.2,0.4},threshold=0.35,isPassable=false,spawn={}},shallow_water={name="Shallow Water",color={0.2,0.4,0.8},threshold=0.45,isPassable=false,spawn={}},beach={name="Beach",color={0.9,0.8,0.5},threshold=0.5,isPassable=true,spawn={{resource="rock",chance=0.05}}},grassy={name="Grassy",color={0.2,0.7,0.2},threshold=0.65,isPassable=true,spawn={{resource="tree",chance=0.02},{resource="fiber_plant",chance=0.2},{resource="herb_plant",chance=0.1}}},forest={name="Forest",color={0.1,0.5,0.1},threshold=0.75,isPassable=true,spawn={{resource="tree",chance=0.4},{resource="herb_plant",chance=0.15}}},suburban={name="Suburban",color={0.6,0.6,0.6},threshold=0.85,isPassable=true,isUrban=true,spawn={{resource="tree",chance=0.01}}},city={name="City",color={0.4,0.4,0.45},threshold=0.92,isPassable=true,isUrban=true,spawn={}},mountain={name="Mountain",color={0.5,0.5,0.5},threshold=1.0,isPassable=true,spawn={{resource="rock",chance=0.2},{resource="coal_vein",chance=0.15},{resource="copper_vein",chance=0.1},{resource="tin_vein",chance=0.1},{resource="iron_vein",chance=0.05}}}}

Data.Images = {}
function Data.loadImages()
    Data.Images={character_sheet=love.graphics.newImage("character_sheet.png"),tree=love.graphics.newImage("tree.png"),rock=love.graphics.newImage("rock.png"),iron_vein=love.graphics.newImage("iron_vein.png"),house=love.graphics.newImage("building_wall.png"),wall=love.graphics.newImage("wall.png"),road=love.graphics.newImage("road.png"),campfire=love.graphics.newImage("campfire.png"),joystick_base=love.graphics.newImage("joystick_base.png"),joystick_nub=love.graphics.newImage("joystick_nub.png"),button_attack=love.graphics.newImage("button_attack.png"),button_menu=love.graphics.newImage("button_menu.png"),coal_vein=love.graphics.newImage("coal_vein.png"),copper_vein=love.graphics.newImage("copper_vein.png"),tin_vein=love.graphics.newImage("tin_vein.png"),fiber_plant=love.graphics.newImage("fiber_plant.png"),herb_plant=love.graphics.newImage("herb_plant.png"),slot=love.graphics.newImage("slot.png"),wood=love.graphics.newImage("wood.png"),stone=love.graphics.newImage("stone.png"),flint=love.graphics.newImage("flint.png"),fiber=love.graphics.newImage("fiber.png"),herb=love.graphics.newImage("herb.png"),coal=love.graphics.newImage("coal.png"),copper_ore=love.graphics.newImage("copper_ore.png"),tin_ore=love.graphics.newImage("tin_ore.png"),iron_ore=love.graphics.newImage("iron_ore.png"),stone_axe=love.graphics.newImage("stone_axe.png"),pickaxe=love.graphics.newImage("pickaxe.png"),stone_wall=love.graphics.newImage("wall.png")}
end

return Data